version: "3.7"

services:
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_BOT_TOKEN= 7201285842:AAE9r2oyYhJpIJ4d8jBYspKYsWUvjmfCJ8k
      - TELEGRAM_CHAT_ID=  -4548170232
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - scrapper

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: deposits

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile.scrapper
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - grafana
      - prometheus
    environment:
      - ALCHEMY_API_KEY=UUThfPb_i7XZKl9sT1LT54JqLckJi6Xg
      - MONGO_URI=mongodb+srv://Denji:Santhosh1@@cluster0.agbc7.mongodb.net/
      - TELEGRAM_NOTIFICATIONS_BOT_TOKEN= 7201285842:AAE9r2oyYhJpIJ4d8jBYspKYsWUvjmfCJ8k
      - TELEGRAM_NOTIFICATIONS_CHAT_ID= -4548170232

volumes:
  grafana_data:
  prometheus_data:
  mongodb_data:
